/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-04-02 21:25:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Srzyl/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1585629187763L));
    _jspx_dependants.put("jar:file:/C:/Users/Srzyl/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Register</title>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template-imports.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<script language = 'javascript'>\n");
      out.write("    function check(input){\n");
      out.write("        if (input.value != document.getElementById('password').value) {\n");
      out.write("            input.setCustomValidity('Password Must be Matching.');\n");
      out.write("        } else {\n");
      out.write("            // input is valid -- reset the error message\n");
      out.write("            input.setCustomValidity('');\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-template.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<form action=\"register\" method=\"POST\">\n");
      out.write("    <div class=\"formGroup container\">\n");
      out.write("        <h1 style = \"color:white;\">Register For An Account</h1>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <label for=\"firstname\"><b>First Name:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"firstname\" placeholder=\"First Name\" pattern=\"[A-Za-z]+\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"lastname\"><b>Last Name:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"lastname\" placeholder=\"Last Name\" pattern=\"[A-Za-z]+\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"email\"><b>Email:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Email\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"password\"><b>Password:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"password\" id = \"password\" class=\"form-control\" name=\"password\" placeholder=\"*****\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"psw-repeat\"><b>Repeat Password:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"password\" id=\"repeatPassword\" class=\"form-control\" name=\"psw-repeat\" oninput=\"check(this)\" placeholder=\"*****\" required>\n");
      out.write("                <br>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <label for=\"street\"><b>Street:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"street\" placeholder=\"Street\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"city\"><b>City:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"city\" placeholder=\"City\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"state\"><b>State:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"state\" placeholder=\"State\" required>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"zipCode\"><b>Zip Code:</b></label>\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"zipCode\"  pattern=\"[0-9]+\" title=\"Need 5 digits\" placeholder=\"Zip Code\" required>\n");
      out.write("                <br>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <br>\n");
      out.write("        <p>By creating an account you agree to our Terms & Privacy</p>\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success registerbtn\" onclick=\"regConfirm.html\">Register</button>\n");
      out.write("        </center>\n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
